### ISSUE TITLE
how i can run forkpi

### ISSUE THREAD

**Issue by eXplOiD1** [crentagon/rbpi_thesis#2]
i dont found a way to run forkpi as service or something.

root@exploid-werkstatt:~/forkpi/forkpi# ./runserver
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named 'django'

**Comment by dimkal88** [comment]
I have the same problem I cant find out how to start the server.

I have something helpfull. Follow it until step 7.
http://raspberrypituts.com/django-raspberry-pi-tutorial/

and edit runserver
sudo nano runserver
edit python3 to python

I end with this error 
File "/home/pi/forkpi/forkpi/forkpi/urls.py", line 20, in <module>
    urlpatterns = patterns('',
NameError: name 'patterns' is not defined

any ideas?

**Comment by eXplOiD1** [comment]
exploid@Werkstatt-Server:~/accesscontrol/forkpi$ $ sudo python3 manage.py runserver 192.168.3.29:8080
sudo: o: command not found
exploid@Werkstatt-Server:~/accesscontrol/forkpi$ sudo python3 manage.py runserver 192.168.3.29:8080
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x751ef0c0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python3.5/dist-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 327, in execute
    autoreload.check_errors(django.setup)()
  File "/usr/local/lib/python3.5/dist-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.5/dist-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.5/dist-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/exploid/accesscontrol/forkpi/records/models.py", line 24, in <module>
    class Log(Model):
  File "/home/exploid/accesscontrol/forkpi/records/models.py", line 26, in Log
    door = ForeignKey('Door')
TypeError: __init__() missing 1 required positional argument: 'on_delete'

**Comment by dimkal88** [comment]
I run these two commands 
sudo pip3 install Django
sudo apt-get install python3-pip
and now I end up with this
 File "/usr/local/lib/python3.5/dist-packages/django/db/backends/postgresql/base.py", line 24, in <module>
    raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2'

**Comment by doomhaMwx** [comment]
Hello!
In part 3.1.2 of the installation/setup process, I am getting a "404: not found" error. It appears that a needed file has already been removed/deleted, or do I need to do something first for this to work? Thanks.


![capture](https://user-images.githubusercontent.com/37734069/37863117-95135028-2f93-11e8-8a02-8a4847bd1b9b.PNG)

**Comment by dimkal88** [comment]
You need to tray different version. I think is 1.7.1

Με εκτίμηση
Καλτσίδης Δημήτρης

Στις Σάβ, 24 Μαρ 2018, 12:48 μ.μ. ο χρήστης doomhaMwx <
notifications@github.com> έγραψε:

**Comment by doomhaMwx** [comment]
^ I am still getting the same error.

**Comment by doomhaMwx** [comment]
So once I have all the files needed (.py files, etc...), what comes next after that?

**Comment by mikha8493** [comment]
Has anyone got this to work?

**Comment by dimkal88** [comment]
I didn't have any time to work with it. If you find out something please
share.



Στις Παρ, 27 Απρ 2018, 6:50 μ.μ. ο χρήστης mikha8493 <
notifications@github.com> έγραψε:
